language: node_js
node_js:
- '8'
- '10'
- '12'
after_success: npm run coverage
env:
- GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json
before_install:
- openssl aes-256-cbc -K $encrypted_8970f4db66b4_key -iv $encrypted_8970f4db66b4_iv
  -in client_secrets.json.enc -out client_secrets.json -d
